trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
      - .gitignore
      - README.md

pr: none

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

name: 3.0$(Rev:.r)

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/**/Emmersion.InfluxDB.IntegrationTests'
    fileType: 'json'
    targetFiles: '**/appsettings.json'

- task: NuGetCommand@2
  displayName: 'Restore from Nuget.org and EmmersionLearning feeds'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '2ee1cde5-9787-4e91-b498-e30a43c5d914'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    packagesToPack: '**/*Tests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/Emmersion.InfluxDB.csproj'
    versioningScheme: 'byBuildNumber'

- task: NuGetCommand@2
  displayName: 'Publish'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '2ee1cde5-9787-4e91-b498-e30a43c5d914'