# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

name: 1.0.$(Date:yyyyMMdd)$(Rev:.r)

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '2ee1cde5-9787-4e91-b498-e30a43c5d914'
    
- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/**/test-integration'
    fileType: 'json'
    targetFiles: '**/appsettings.json'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    packagesToPack: '**/EL.InfluxDB.UnitTests.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    packagesToPack: '**/EL.InfluxDB.IntegrationTests.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/EL.InfluxDB.csproj'
    versioningScheme: 'byBuildNumber'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '2ee1cde5-9787-4e91-b498-e30a43c5d914'